"""empty message

Revision ID: e1a6a0a6c09d
Revises: d26b09ba10fc
Create Date: 2020-06-30 21:29:13.945866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a6a0a6c09d'
down_revision = 'd26b09ba10fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment_items', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipment_items', 'quantity')
    # ### end Alembic commands ###
