"""empty message

Revision ID: fa8d5fe0522c
Revises: e1a6a0a6c09d
Create Date: 2020-07-01 10:05:43.092780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8d5fe0522c'
down_revision = 'e1a6a0a6c09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shipment_items')
    op.drop_table('Shipment')
    op.drop_table('Item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Item_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Item_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Shipment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Shipment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Shipment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Shipment_items',
    sa.Column('shipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], name='Shipment_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['shipment_id'], ['Shipment.id'], name='Shipment_items_shipment_id_fkey'),
    sa.PrimaryKeyConstraint('shipment_id', 'item_id', name='Shipment_items_pkey')
    )
    # ### end Alembic commands ###
